name = "junze-web"
account_id = "75272e1ccb256bae87f8c7419053c02b"
main = "src/index.js"
compatibility_date = "2026-07-17"

[[d1_databases]]
binding = "NAV_DB"
database_name = "book"
database_id = "f9eb1e79-ac15-40bd-8439-b579629f00ba"

[[kv_namespaces]]
binding = "NAV_AUTH"
id = "7a732c8f964d4cedbacba852e82eba7b"
